version: "3"

services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    deploy:
      replicas: 1

  lb:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"